module.exports = {
  created_at: 'Wed May 11 20:28:42 +0000 2016',
  id: 730494867059527700,
  id_str: '730494867059527680',
  text: 'a test generated tweet 0.9546235366724432',
  truncated: false,
  entities: { hashtags: [], symbols: [], user_mentions: [], urls: [] },
  source: '<a href="https://github.com/Sabine-Sardine/app" rel="nofollow">botlbot</a>',
  in_reply_to_status_id: null,
  in_reply_to_status_id_str: null,
  in_reply_to_user_id: null,
  in_reply_to_user_id_str: null,
  in_reply_to_screen_name: null,
  user: {
    id: 727615201575469000,
    id_str: '727615201575469056',
    name: 'botltest',
    screen_name: 'botltest',
    location: '',
    description: '',
    url: null,
    entities: { description: [Object] },
    protected: false,
    followers_count: 0,
    friends_count: 20,
    listed_count: 0,
    created_at: 'Tue May 03 21:45:57 +0000 2016',
    favourites_count: 0,
    utc_offset: null,
    time_zone: null,
    geo_enabled: false,
    verified: false,
    statuses_count: 38,
    lang: 'en',
    contributors_enabled: false,
    is_translator: false,
    is_translation_enabled: false,
    profile_background_color: 'F5F8FA',
    profile_background_image_url: null,
    profile_background_image_url_https: null,
    profile_background_tile: false,
    profile_image_url: 'http://abs.twimg.com/sticky/default_profile_images/default_profile_3_normal.png',
    profile_image_url_https: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_3_normal.png',
    profile_link_color: '2B7BB9',
    profile_sidebar_border_color: 'C0DEED',
    profile_sidebar_fill_color: 'DDEEF6',
    profile_text_color: '333333',
    profile_use_background_image: true,
    has_extended_profile: false,
    default_profile: true,
    default_profile_image: true,
    following: false,
    follow_request_sent: false,
    notifications: false,
  },
  geo: null,
  coordinates: null,
  place: null,
  contributors: null,
  is_quote_status: false,
  retweet_count: 0,
  favorite_count: 0,
  favorited: false,
  retweeted: false,
  lang: 'en',
};
